# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(verbose_name='data published')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('legend', models.CharField(max_length=200)),
                ('ingress', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
