# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170729_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
