# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170729_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news_images/'),
        ),
    ]
