# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('portrait', models.FileField(upload_to='member_portraits/')),
            ],
        ),
    ]
